"""ISO 639 language code mapping and utilities."""

from typing import Optional

# ISO 639-2/B and ISO 639-1 to human-readable language names
# Covers all common languages found in MKV files
LANGUAGE_MAP: dict[str, str] = {
    # ISO 639-2/B codes (3-letter)
    "aar": "Afar",
    "abk": "Abkhazian",
    "afr": "Afrikaans",
    "aka": "Akan",
    "amh": "Amharic",
    "ara": "Arabic",
    "arg": "Aragonese",
    "asm": "Assamese",
    "ava": "Avaric",
    "ave": "Avestan",
    "aym": "Aymara",
    "aze": "Azerbaijani",
    "bak": "Bashkir",
    "bam": "Bambara",
    "bel": "Belarusian",
    "ben": "Bengali",
    "bis": "Bislama",
    "bod": "Tibetan",
    "bos": "Bosnian",
    "bre": "Breton",
    "bul": "Bulgarian",
    "cat": "Catalan",
    "ces": "Czech",
    "cha": "Chamorro",
    "che": "Chechen",
    "chu": "Church Slavic",
    "chv": "Chuvash",
    "cor": "Cornish",
    "cos": "Corsican",
    "cre": "Cree",
    "cym": "Welsh",
    "dan": "Danish",
    "deu": "German",
    "div": "Divehi",
    "dzo": "Dzongkha",
    "ell": "Greek",
    "eng": "English",
    "epo": "Esperanto",
    "est": "Estonian",
    "eus": "Basque",
    "ewe": "Ewe",
    "fao": "Faroese",
    "fas": "Persian",
    "fij": "Fijian",
    "fin": "Finnish",
    "fra": "French",
    "fry": "Western Frisian",
    "ful": "Fulah",
    "gla": "Scottish Gaelic",
    "gle": "Irish",
    "glg": "Galician",
    "glv": "Manx",
    "grn": "Guarani",
    "guj": "Gujarati",
    "hat": "Haitian",
    "hau": "Hausa",
    "hbs": "Serbo-Croatian",
    "heb": "Hebrew",
    "her": "Herero",
    "hin": "Hindi",
    "hmo": "Hiri Motu",
    "hrv": "Croatian",
    "hun": "Hungarian",
    "hye": "Armenian",
    "ibo": "Igbo",
    "ido": "Ido",
    "iii": "Sichuan Yi",
    "iku": "Inuktitut",
    "ile": "Interlingue",
    "ina": "Interlingua",
    "ind": "Indonesian",
    "ipk": "Inupiaq",
    "isl": "Icelandic",
    "ita": "Italian",
    "jav": "Javanese",
    "jpn": "Japanese",
    "kal": "Kalaallisut",
    "kan": "Kannada",
    "kas": "Kashmiri",
    "kat": "Georgian",
    "kau": "Kanuri",
    "kaz": "Kazakh",
    "khm": "Khmer",
    "kik": "Kikuyu",
    "kin": "Kinyarwanda",
    "kir": "Kirghiz",
    "kom": "Komi",
    "kon": "Kongo",
    "kor": "Korean",
    "kua": "Kuanyama",
    "kur": "Kurdish",
    "lao": "Lao",
    "lat": "Latin",
    "lav": "Latvian",
    "lim": "Limburgish",
    "lin": "Lingala",
    "lit": "Lithuanian",
    "ltz": "Luxembourgish",
    "lub": "Luba-Katanga",
    "lug": "Ganda",
    "mac": "Macedonian",
    "mah": "Marshallese",
    "mal": "Malayalam",
    "mar": "Marathi",
    "mkd": "Macedonian",
    "mlg": "Malagasy",
    "mlt": "Maltese",
    "mon": "Mongolian",
    "mri": "Maori",
    "msa": "Malay",
    "may": "Malay",
    "mya": "Burmese",
    "nau": "Nauru",
    "nav": "Navajo",
    "nbl": "South Ndebele",
    "nde": "North Ndebele",
    "ndo": "Ndonga",
    "nep": "Nepali",
    "nld": "Dutch",
    "dut": "Dutch",
    "nno": "Norwegian Nynorsk",
    "nob": "Norwegian Bokmål",
    "nor": "Norwegian",
    "nya": "Chichewa",
    "oci": "Occitan",
    "oji": "Ojibwa",
    "ori": "Oriya",
    "orm": "Oromo",
    "oss": "Ossetian",
    "pan": "Punjabi",
    "per": "Persian",
    "pli": "Pali",
    "pol": "Polish",
    "por": "Portuguese",
    "pus": "Pashto",
    "que": "Quechua",
    "roh": "Romansh",
    "ron": "Romanian",
    "rum": "Romanian",
    "run": "Rundi",
    "rus": "Russian",
    "sag": "Sango",
    "san": "Sanskrit",
    "sin": "Sinhala",
    "slk": "Slovak",
    "slo": "Slovak",
    "slv": "Slovenian",
    "sme": "Northern Sami",
    "smo": "Samoan",
    "sna": "Shona",
    "snd": "Sindhi",
    "som": "Somali",
    "sot": "Southern Sotho",
    "spa": "Spanish",
    "sqi": "Albanian",
    "alb": "Albanian",
    "srd": "Sardinian",
    "srp": "Serbian",
    "ssw": "Swati",
    "sun": "Sundanese",
    "swa": "Swahili",
    "swe": "Swedish",
    "tah": "Tahitian",
    "tam": "Tamil",
    "tat": "Tatar",
    "tel": "Telugu",
    "tgk": "Tajik",
    "tgl": "Tagalog",
    "tha": "Thai",
    "tib": "Tibetan",
    "tir": "Tigrinya",
    "ton": "Tonga",
    "tsn": "Tswana",
    "tso": "Tsonga",
    "tuk": "Turkmen",
    "tur": "Turkish",
    "twi": "Twi",
    "uig": "Uighur",
    "ukr": "Ukrainian",
    "urd": "Urdu",
    "uzb": "Uzbek",
    "ven": "Venda",
    "vie": "Vietnamese",
    "vol": "Volapük",
    "wln": "Walloon",
    "wol": "Wolof",
    "xho": "Xhosa",
    "yid": "Yiddish",
    "yor": "Yoruba",
    "zha": "Zhuang",
    "zho": "Chinese",
    "chi": "Chinese",
    "zul": "Zulu",
    # ISO 639-1 codes (2-letter) - common ones
    "aa": "Afar",
    "ab": "Abkhazian",
    "af": "Afrikaans",
    "am": "Amharic",
    "ar": "Arabic",
    "as": "Assamese",
    "az": "Azerbaijani",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bn": "Bengali",
    "bo": "Tibetan",
    "bs": "Bosnian",
    "ca": "Catalan",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "el": "Greek",
    "en": "English",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "fi": "Finnish",
    "fr": "French",
    "ga": "Irish",
    "gl": "Galician",
    "gu": "Gujarati",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hu": "Hungarian",
    "hy": "Armenian",
    "id": "Indonesian",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "ka": "Georgian",
    "kk": "Kazakh",
    "km": "Khmer",
    "kn": "Kannada",
    "ko": "Korean",
    "ku": "Kurdish",
    "ky": "Kirghiz",
    "la": "Latin",
    "lo": "Lao",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mr": "Marathi",
    "ms": "Malay",
    "mt": "Maltese",
    "my": "Burmese",
    "nb": "Norwegian Bokmål",
    "ne": "Nepali",
    "nl": "Dutch",
    "nn": "Norwegian Nynorsk",
    "no": "Norwegian",
    "or": "Oriya",
    "pa": "Punjabi",
    "pl": "Polish",
    "ps": "Pashto",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sq": "Albanian",
    "sr": "Serbian",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu",
    "tg": "Tajik",
    "th": "Thai",
    "tl": "Tagalog",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "vi": "Vietnamese",
    "zh": "Chinese",
    "zu": "Zulu",
}


def get_language_name(code: Optional[str]) -> str:
    """Get human-readable language name from ISO 639 code.

    Args:
        code: ISO 639-1 (2-letter) or ISO 639-2 (3-letter) language code.

    Returns:
        Human-readable language name, or "Unknown" if code is not recognized.
    """
    if not code or code.lower() in ("und", "undetermined", ""):
        return "Unknown"
    return LANGUAGE_MAP.get(code.lower(), f"Unknown ({code})")


def get_language_code(name: str) -> Optional[str]:
    """Get ISO 639 code from a human-readable language name.

    Args:
        name: Human-readable language name (case-insensitive).

    Returns:
        The first matching 3-letter ISO 639-2 code, or None if not found.
    """
    name_lower = name.lower()
    for code, lang_name in LANGUAGE_MAP.items():
        if lang_name.lower() == name_lower and len(code) == 3:
            return code
    return None


def is_valid_language_code(code: str) -> bool:
    """Check if a string is a valid ISO 639 language code.

    Args:
        code: Language code to validate.

    Returns:
        True if the code is recognized.
    """
    return code.lower() in LANGUAGE_MAP
